USE PRACTICA_DISPARADORES;

SELECT * FROM VENDEDOR;
SELECT * FROM CLIENTE;
SELECT * FROM INVENTARIO;
SELECT * FROM VENTAS;
INSERT INTO VENDEDOR(NOMBRE_VENDEDOR, PUNTOS) VALUES ('ANDRES BELLORIN', 0);
INSERT INTO CLIENTE(NOMBRE_CLIENTE) VALUES('CLAUDIA PACHERRES');
INSERT INTO INVENTARIO(CANTIDAD_PRODUCTO) VALUES (20);
INSERT INTO VENTAS(idCLIENTE, idVENDEDOR, idPRODUCTO, CANTIDAD) VALUES (1,1,1,3);

